### ISSUE TITLE
Ubuntu 24.04 support

### ISSUE THREAD

**Issue by roworu** [dlenski/gp-saml-gui#98] opened 2024-04-18 12:35 UTC
Hello. I found out, that on Ubuntu 24.04, that is planned to release in a few weeks, there is an issue during installation of dependencies:
```
sudo apt install python3-gi gir1.2-gtk-3.0 gir1.2-webkit2-4.0

E: Package 'gir1.2-webkit2-4.0' has no installation candidate
```

But there is a newer package version, installed by default:

```
apt search gir1.2-webkit2 
Sorting... Done
Full Text Search... Done
gir1.2-webkit2-4.1/noble,now 2.44.0-2 amd64 [installed]
  Web content engine library for GTK - GObject introspection data

```

And therefore, we getting an error during startup due to this line in code:

`gi.require_version('WebKit2', '4.0')`

If I just change it to `4.1` program starts and working fine.

Do we need to just update requirements? Or remove this line?

AFAIK, not all distros ship webkit2 version 4.1, so there might be reason to add additional check, if one of them (4.1 or 4.0) is presented.

**Comment by roworu** [comment] 2024-04-18 12:36
@dlenski , please, comment on which way you think is best, I would be happy to provide PR. Thank you.

**Comment by eitzenbe** [comment] 2024-04-27 12:07
any updates on this issue? recently set up a new laptop and am now blocked from access our company internals

**Comment by eitzenbe** [comment] 2024-05-01 12:46
Global-protect releases a new version for 24.04 all sorted out thanks

**Comment by pboushy** [comment] 2024-05-07 18:30
This is resolved in https://github.com/dlenski/gp-saml-gui/commit/adf8261424a5287124dde7daa99a94675a89f5e8

**Comment by dlenski** [comment] 2024-05-09 12:01
Duplicate of #92, resolved now via https://github.com/dlenski/gp-saml-gui/commit/adf8261424a5287124dde7daa99a94675a89f5e8

**Closed by dlenski** 2024-05-09 12:01 UTC
